namespace: trino-controller
serviceAccount: trino-controller
image: cloudcheflabs/trino-controller:v1.1.0
imagePullPolicy: Always
replicas: 1
resources:
  requests:
    cpu: 200m
    memory: 1Gi
  limits:
    cpu: 300m
    memory: 1500Mi
priorityClassName: ""
annotations: null
affinity: null
tolerations: null
nodeSelector: null
hostNetwork: false
dnsPolicy: Default

# spring boot server
server:
  port: 8093
trino:
  operator:
    namespace: trino-operator
    restUri: "http://trino-operator-service.trino-operator.svc:8092"
  gateway:
    publicEndpoint: "https://trino-gw-proxy.example.com"
    proxyHostName: "trino-gw-proxy.example.com"
    restHostName: "trino-gw-rest.example.com"
    storageClass: "oci"
    restUri: "http://trino-gateway-rest-service.trino-gateway.svc:8099"
