cluster:
  name: {{ es_cluster_name }}
  publish:
    timeout: 300s
  join:
    timeout: 300s
  initial_master_nodes:
{% for item in es_initial_master_nodes %}
  - "{{ item }}"
{% endfor %}
network:
  host: 0.0.0.0
http:
  publish_port: {{ es_http_publish_port }}
  port: {{ es_http_publish_port }}
transport:
  publish_port: {{ es_transport_publish_port }}
  tcp:
    port: {{ es_transport_publish_port }}
discovery:
  seed_hosts:
{% for item in es_seed_hosts %}
  - "{{ item }}"
{% endfor %}
path:
  data:
{% for item in es_data_dir %}
  - "{{ item }}"
{% endfor %}
  logs: {{ es_log_dir }}
bootstrap.memory_lock: true
indices.query.bool.max_clause_count: 10000

