- hosts: "{{ target_hosts }}"
  remote_user: "{{ exec_user }}"
  become: true

  vars:
  - ansible_ssh_user: "{{ exec_user }}"

  roles:
  - role: "{{ role_prefix }}/install"
    when: ("{{ run_option }}" == "install")

  - role: "{{ role_prefix }}/uninstall"
    when: ("{{ run_option }}" == "uninstall")

  - role: "{{ role_prefix }}/uninstall"
    when: ("{{ run_option }}" == "reinstall")

  - role: "{{ role_prefix }}/install"
    when: ("{{ run_option }}" == "reinstall")