- hosts: "{{ target_hosts }}"
  remote_user: "{{ exec_user }}"
  become: true

  vars:
  - ansible_ssh_user: "{{ exec_user }}"

  roles:
    - role: "cli/uninstall"
    - role: "apiserver/uninstall"
    - role: "authorizer/uninstall"
    - role: "vault/uninstall"
    - role: "mysql/uninstall"
    - role: "prerequisite/uninstall"
    - role: "prerequisite/install"
    - role: "mysql/install"
    - role: "vault/install"
    - role: "authorizer/install"
    - role: "apiserver/install"
    - role: "cli/install"

