- name: stop authorizer
  shell: "{{ item }}"
  args:
    executable: /bin/bash
    chdir: "{{ authorizer_home_dir }}"
  with_items:
    - "./stop-authorizer.sh"
  become_user: "{{ dataroaster_exec_user }}"
  ignore_errors: true

- name: delete authorizer directory
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ authorizer_home_dir }}"
  become: true
  ignore_errors: true