server:
  port: 8081
  servlet:
    context-path: /authorizer


    
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver  
    url: jdbc:mysql://localhost:3306/dataroaster
    username: dataroaster
    password: dataroaster123
    hikari:
      maximum-pool-size: 10
      max-lifetime: 30

security:
  oauth2:
    resource:
      jwt:
        publicKeyPath: authorizer.pub
        keypair:
          path: authorizer.jks
          alias: authorizer
          keypass: icarus
        accessTokenValiditySeconds: 36000
        refreshTokenValiditySeconds: 86400