namespace: redash
image: redash/redash:10.0.0-beta.b49597
dnsPolicy: Default
storage:
  storageClass: oci
  size: 10
service:
  type: ClusterIP

server:
  port: 5000

# ingress.
ingress:
  enabled: false
  ingressClassName: nginx
  hostName: dataroaster-redash.cloudchef-labs.com

# cert-manager.
certManager:
  clusterIssue: letsencrypt-prod