- name: create dataroaster user
  user:
    name: dataroaster
    state: present
    createhome: yes
    home: "{{ dataroaster_home_dir }}"
  become: true


- name: create dataroaster directories
  file:
    path: "{{ item }}"
    state: directory
    owner: dataroaster
    group: dataroaster
    mode: 0755
  with_items:
    - "{{ dataroaster_home_dir }}"
    - "{{ cli_temp_dir }}" 
  become: true

- name: download cli distribution
  get_url:
    url: "https://github.com/cloudcheflabs/dataroaster/releases/download/{{ dataroaster_version }}/cli-{{ dataroaster_version }}-dist.tgz"
    dest: "{{ cli_temp_dir }}"
    mode: '0755'
  become: true


- name: extract cli distribution
  shell: "{{ item }}"
  args:
    executable: /bin/bash
    chdir: "{{ cli_temp_dir }}"
  with_items:
    - "tar zxvf cli-*-dist.tgz"
    - "cp cli/dataroaster {{ cli_binary }}"
    - "chmod a+x {{ cli_binary }}"
  become: true

- name: delete cli directory
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ cli_temp_dir }}"
  become: true
  ignore_errors: true

