---
apiVersion: v1
kind: Service
metadata:
  name: metabase-service
  namespace: {{ .Values.namespace }}
  labels:
    app: metabase
    component: dataroaster
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.server.port }}
      targetPort: ui
      protocol: TCP
      name: ui
  selector:
    app: metabase