apiVersion: apps/v1
kind: Deployment
metadata:
  name: trino-controller
  labels:
    app: trino-controller
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: trino-controller
  template:
    metadata:
      labels:
        app: trino-controller
      annotations:
      {{- toYaml $.Values.tolerations | nindent 8 }}
    spec:
      affinity:
      {{- toYaml $.Values.affinity | nindent 8 }}
      tolerations:
      {{- toYaml $.Values.tolerations | nindent 8 }}
      nodeSelector:
      {{- toYaml $.Values.nodeSelector | nindent 8 }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      hostNetwork: {{ .Values.hostNetwork }}
      serviceAccountName: {{ .Values.serviceAccount }}
      dnsPolicy: {{ .Values.dnsPolicy }}
      containers:
        - name: trino-controller
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          resources: 
          {{- toYaml $.Values.resources | nindent 12 }}
          command:
            - "./run-trino-controller.sh"
          volumeMounts:
            - name: trino-controller-volume
              mountPath: /opt/trino-controller/conf/application.properties
              subPath: application.properties
            - name: trino-controller-volume
              mountPath: /opt/trino-controller/conf/application-prod.yml
              subPath: application-prod.yml
          ports:
            - name: rest
              containerPort: {{ .Values.server.port }}
              protocol: TCP
      volumes:
        - name: trino-controller-volume
          configMap:
            name: trino-controller