apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: trino-worker
  namespace: {{ namespace }}
spec:
  maxReplicas: {{ maxReplicas }}
  minReplicas: {{ minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: trino-worker
  targetCPUUtilizationPercentage: {{ targetCPUUtilizationPercentage }}
