expose:
  tls:
    enabled: true
    certSource: secret
    secret:
      secretName: "harbor-core-test.cloudchef-labs.com-tls"
      notarySecretName: "harbor-notary-test.cloudchef-labs.com-tls"
  ingress:
    hosts:
      core: harbor-core-test.cloudchef-labs.com
      notary: harbor-notary-test.cloudchef-labs.com
    annotations:
      ingress.kubernetes.io/ssl-redirect: "true"
      ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      kubernetes.io/ingress.class: "nginx"
      cert-manager.io/cluster-issuer: letsencrypt-prod
externalURL: https://harbor-core-test.cloudchef-labs.com
persistence:
  enabled: true
  resourcePolicy: "keep"
  persistentVolumeClaim:
    registry:
      storageClass: "ceph-rbd-sc"
      accessMode: ReadWriteOnce
      size: 5Gi
    chartmuseum:
      storageClass: "ceph-rbd-sc"
      accessMode: ReadWriteOnce
      size: 5Gi
    jobservice:
      storageClass: "ceph-rbd-sc"
      accessMode: ReadWriteOnce
      size: 1Gi
    database:
      storageClass: "ceph-rbd-sc"
      accessMode: ReadWriteOnce
      size: 1Gi
    redis:
      storageClass: "ceph-rbd-sc"
      accessMode: ReadWriteOnce
      size: 1Gi
    trivy:
      storageClass: "ceph-rbd-sc"
      accessMode: ReadWriteOnce
      size: 5Gi
  imageChartStorage:
    disableredirect: true
    type: s3
    s3:
      region: us-west-1
      bucket: harbor
      accesskey: TOW32G9ULH63MTUI6NNW
      secretkey: jXqViVmSqIDTEKKKzdgSssHVykBrX4RrlnSeVgMi
      regionendpoint: https://ceph-rgw-test.cloudchef-labs.com

