{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redash-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.certManager.clusterIssue }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
    - host: {{ .Values.ingress.hostName }}
      http:
        paths:
          - backend:
              service:
                name: redash
                port:
                  number: {{ .Values.server.port }}
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - {{ .Values.ingress.hostName }}
      secretName: {{ .Values.ingress.hostName }}-tls
{{- end }}