apiVersion: "helm-operator.cloudchef-labs.com/v1beta1"
kind: HelmChart
metadata:
  name: jupyterhub
  namespace: dataroaster-operator
spec:
  repo: https://charts.bitnami.com/bitnami
  chartName: jupyterhub
  name: jupyterhub
  version: 1.3.6
  namespace: jupyterhub
  values: |
    hub:
      service:
        type: LoadBalancer
    singleuser:
      image:
        registry: docker.io
        repository: cloudcheflabs/dataroaster-bitnami-jupyter
        tag: 1.5.0
        pullPolicy: Always
      persistence:
        storageClass: oci
        size: 15Gi