- name: stop apiserver
  shell: "{{ item }}"
  args:
    executable: /bin/bash
    chdir: "{{ apiserver_home_dir }}"
  with_items:
    - "./stop-apiserver.sh"
  become_user: "{{ dataroaster_exec_user }}"

- name: delete apiserver directory
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ apiserver_home_dir }}"
  become: true
  ignore_errors: true