apiVersion: "helm-operator.cloudchef-labs.com/v1beta1"
kind: HelmChart
metadata:
  name: hive-metastore-mysql
  namespace: dataroaster-operator
spec:
  repo: https://cloudcheflabs.github.io/mysql-helm-repo/
  chartName: dataroastermysql
  name: mysql
  version: v1.0.2
  namespace: {{ namespace }}
  values: |
    storage:
      storageClass: {{ storageClass }}
      size: {{ size }}Gi