namespace: trino-operator
serviceAccount: trino-operator
image: cloudcheflabs/trino-operator:v3.1.0
imagePullPolicy: Always
resources:
  requests:
    cpu: 200m
    memory: 1Gi
  limits:
    cpu: 300m
    memory: 1500Mi
priorityClassName: ""
annotations: null
affinity: null
tolerations: null
nodeSelector: null
hostNetwork: false
server:
    port: 8092
