- name: Stopping kibana
  shell: "kill $(cat pid)"
  args:
    chdir: "{{ item }}"
    executable: /bin/bash
  become_user: kibana
  with_items:
    - "{{ kibana_home }}"
  when: inventory_hostname in groups['kibana']
  ignore_errors: true

- name: Stopping elasticsearch
  shell: "kill $(cat pid)"
  args:
    chdir: "{{ item }}"
    executable: /bin/bash
  become_user: elasticsearch
  with_items:
    - "{{ es_home }}"
  ignore_errors: true

- name: Removing elasticsearch directories
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ es_home }}"
    - "{{ es_data_dir }}"
    - "{{ es_log_dir }}"
    - "/etc/security/limits.d/elasticsearch.conf"

- name: Removing kibana directories
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ kibana_home }}"
    - "{{ kibana_data_dir }}"
  when: inventory_hostname in groups['kibana']

- name: Removing Users
  user:
    name: "{{ item }}"
    state: absent
  become: true
  with_items:
    - "elasticsearch"
    - "kibana"
  ignore_errors: true





