apiVersion: "helm-operator.cloudchef-labs.com/v1beta1"
kind: HelmChart
metadata:
  name: trino-gateway
  namespace: {{ customResourceNamespace }}
spec:
  repo: https://cloudcheflabs.github.io/trino-gateway-helm-repo/
  chartName: dataroaster-trino-gateway
  name: trino-gateway
  version: v1.0.3
  namespace: trino-gateway
  values: |
    ingress:
      proxyHostName: {{ proxyHostName }}
      restHostName: {{ restHostName }}