apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  name: {{ name }}-ingress
  namespace: {{ namespace }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ clusterHostName }}
      http:
        paths:
          - backend:
              service:
                name: trino-coordinator-service
                port:
                  number: 8080
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - {{ clusterHostName }}
      secretName: {{ clusterHostName }}-tls