apiVersion: "helm-operator.cloudchef-labs.com/v1beta1"
kind: HelmChart
metadata:
  name: trino-gateway
  namespace: {{ customResourceNamespace }}
spec:
  repo: https://cloudcheflabs.github.io/trino-gateway-helm-repo/
  chartName: dataroaster-trino-gateway
  name: trino-gateway
  version: v1.5.0
  namespace: trino-gateway
  values: |
    ingress:
      proxyHostName: {{ proxyHostName }}
      restHostName: {{ restHostName }}
    trino:
      proxy:
        publicEndpoint: {{ publicEndpoint }}
    dataroastermysql:
      storage:
        storageClass: {{ storageClass }}
    redis:
      global:
        storageClass: {{ storageClass }}
      replica:
        replicaCount: 1