apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: {{ .Values.namespace }}
data:
  logstash.conf: |-
    input {
      beats {
          port => "5044"
      }
    }
    filter {
      # Container logs are received with variable named index_prefix
      # Since it is in json format, we can decode it via json filter plugin.
      if [index_prefix] == "k8s-logs" {

        if [message] =~ /^\{.*\}$/ {
          json {
            source => "message"
            skip_on_invalid_json => true
          }
        }
      }
      # do not expose index_prefix field to kibana
      mutate {
        # @metadata is not exposed outside of Logstash by default.
        add_field => { "[@metadata][index_prefix]" => "%{index_prefix}-%{+YYYY.MM.dd}" }
        # since we added index_prefix to metadata, we no longer need ["index_prefix"] field.
        remove_field => ["index_prefix"]
      }
    }
    output {
      # You can uncomment this line to investigate the generated events by the logstash.
      #stdout { codec => rubydebug }
      elasticsearch {
          {{- $hostsLen := len .Values.elasticsearch.hosts -}}
          {{- $hostsLenMinusOne := sub $hostsLen 1 -}}
          hosts => [{{ range $index, $host := .Values.elasticsearch.hosts }} "{{ $host }}"{{ if lt $index $hostsLenMinusOne }},{{ end }}{{ end }}]
          template_overwrite => false
          manage_template => false
          # The events will be stored in elasticsearch under previously defined index_prefix value.
          index => "%{[@metadata][index_prefix]}"
          sniffing => false
      }
    }
  logstash.yml: |
    http:
      host: "0.0.0.0"
    xpack:
      monitoring:
        enabled: true
        elasticsearch:
          hosts:
{{ toYaml .Values.elasticsearch.hosts | indent 12 }}
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: logstash
  namespace: {{ .Values.namespace }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      hostname: logstash
      containers:
        - name: logstash
          ports:
            - containerPort: 5044
              name: logstash
          image: docker.elastic.co/logstash/logstash:7.12.1
          volumeMounts:
            - name: logstash-config
              mountPath: /usr/share/logstash/pipeline/logstash.conf
              subPath: logstash.conf
            - name: logstash-yaml
              mountPath: /usr/share/logstash/config/logstash.yml
              subPath: logstash.yml
          command:
            - logstash
      volumes:
        - name: logstash-config
          configMap:
            name: logstash-config
        - name: logstash-yaml
          configMap:
            name: logstash-config
---
kind: Service
apiVersion: v1
metadata:
  name: logstash
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: logstash
  ports:
    - protocol: TCP
      port: 5044
      targetPort: 5044
      name: logstash
