apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataroaster-operator
  labels:
    app: dataroaster-operator
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: dataroaster-operator
  template:
    metadata:
      labels:
        app: dataroaster-operator
      annotations:
      {{- toYaml $.Values.tolerations | nindent 8 }}
    spec:
      affinity:
      {{- toYaml $.Values.affinity | nindent 8 }}
      tolerations:
      {{- toYaml $.Values.tolerations | nindent 8 }}
      nodeSelector:
      {{- toYaml $.Values.nodeSelector | nindent 8 }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      hostNetwork: {{ .Values.hostNetwork }}
      serviceAccountName: {{ .Values.serviceAccount }}
      containers:
        - name: dataroaster-operator
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          resources: 
          {{- toYaml $.Values.resources | nindent 12 }}
          command:
            - "./run-dataroaster-operator.sh"
          volumeMounts:
            - name: dataroaster-operator-volume
              mountPath: /opt/dataroaster-operator/conf/application.properties
              subPath: application.properties
            - name: dataroaster-operator-volume
              mountPath: /opt/dataroaster-operator/conf/application-prod.yml
              subPath: application-prod.yml
          ports:
            - name: rest
              containerPort: {{ .Values.server.port }}
              protocol: TCP
      volumes:
        - name: dataroaster-operator-volume
          configMap:
            name: dataroaster-operator