---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.dependency.'dataroaster-trino-operator'.namespace }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.dependency.'dataroaster-spark-operator'.namespace }}