# spring boot server
server:
  port: 8099
  servlet:
    context-path: /
# trino proxy
trino:
  proxy:
    port: 18080
    authentication: false
    tls:
      enabled: false
      keystorePath: /home/opc/keystore.jks
      keystorePass: changeit
      trustStorePath: /home/opc/.keystore
      trustStorePass: changeit
    threadPool:
      maxThreads: 100
      minThreads: 10
      idleTimeout: 120
    publicEndpoint: "https://trino-gateway-proxy-test.cloudchef-labs.com"
# jdbc
jdbc:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/trino_proxy?useSSL=false
  user: trino
  pass: Trino123!

# hibernate
hibernate:
  dialect: org.hibernate.dialect.MySQL5Dialect
  show_sql: true
  globally_quoted_identifiers: true
# redis
redis:
  host: localhost
  port: 6379

