- name: start apiserver
  shell: "{{ item }}"
  args:
    executable: /bin/bash
    chdir: "{{ apiserver_home_dir }}"
  with_items:
    - "./start-apiserver.sh"
  become_user: "{{ dataroaster_exec_user }}"