apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: livy-log-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.livy.storageSize }}
  storageClassName: {{ .Values.livy.storageClass }}