---
apiVersion: v1
kind: Service
metadata:
  name: livy-service
  namespace: {{ .Values.namespace }}
  labels:
    app: livy
    component: dataroaster
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.server.port }}
      targetPort: rest
      protocol: TCP
      name: rest
  selector:
    app: livy