- name: stop authorizer
  shell: "{{ item }}"
  args:
    executable: /bin/bash
    chdir: "{{ authorizer_home_dir }}"
  with_items:
    - "./stop-authorizer.sh"
  become_user: "{{ dataroaster_exec_user }}"