alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: {{ storageClass }}
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: {{ storageSize }}Gi
prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: {{ storageClass }}
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: {{ storageSize }}Gi