# spring boot server
server:
  port: 8093
  servlet:
    context-path: /
trino:
  gateway:
    publicEndpoint: "https://trino-gateway-proxy-test.cloudchef-labs.com"
    proxyHostName: trino-gateway-proxy-test.cloudchef-labs.com
    restHostName: trino-gateway-rest-test.cloudchef-labs.com
    storageClass: @trino.gateway.storageClass@
    restUri: "http://localhost:8099"
  operator:
    restUri: "http://localhost:8092"

