hub:
  config:
    GitHubOAuthenticator:
      client_id: "0b322767446baedb3203"
      client_secret: "828688ff8be545b6434df2dbb2860a1160ae1517"
      oauth_callback_url: "https://jupyterhub-test.cloudchef-labs.com/hub/oauth_callback"
  db:
    pvc:
      storageClassName: ceph-rbd-sc
proxy:
  secretToken: 7da9d7398a08337aed8b4f24fbc51a02966a900a594f592d1d27ae25701baead
singleuser:
  image:
    name: cloudcheflabs/dataroaster-jupyter
    tag: '1.1.3'
    pullPolicy: Always
  storage:
    capacity: 1Gi
    dynamic:
      storageClass: ceph-rbd-sc
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - jupyterhub-test.cloudchef-labs.com
  pathSuffix:
  pathType: Prefix
  tls:
    - hosts:
      - jupyterhub-test.cloudchef-labs.com
      secretName: jupyterhub-test.cloudchef-labs.com-tls
