apiVersion: v1
kind: ConfigMap
metadata:
  name: trino-gateway
  namespace: {{ .Values.namespace }}
  labels:
    app: trino-gateway
data:
  application.properties: |
    spring.profiles.active=@api.spring.profiles.active@
  application-prod.yml: |
    # spring boot server
    server:
      port: {{ .Values.server.port }}
      servlet:
        context-path: /
    # trino proxy
    trino:
      proxy:
        port: {{ .Values.trino.proxy.port }}
        authentication: {{ .Values.trino.proxy.authentication }}
        tls:
          enabled: {{ .Values.trino.proxy.tls.enabled }}
          keystorePath: {{ .Values.trino.proxy.tls.keystorePath }}
          keystorePass: {{ .Values.trino.proxy.tls.keystorePass }}
          trustStorePath: {{ .Values.trino.proxy.tls.trustStorePath }}
          trustStorePass: {{ .Values.trino.proxy.tls.trustStorePass }}
        threadPool:
          maxThreads: {{ .Values.trino.proxy.threadPool.maxThreads }}
          minThreads: {{ .Values.trino.proxy.threadPool.minThreads }}
          idleTimeout: {{ .Values.trino.proxy.threadPool.idleTimeout }}
        publicEndpoint: {{ .Values.trino.proxy.publicEndpoint }}
    # jdbc
    jdbc:
      driverClassName: com.mysql.jdbc.Driver
      url: {{ template "jdbc.url" . }}
      user: {{ .Values.jdbc.user }}
      pass: {{ .Values.jdbc.pass }}  
    # hibernate
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      show_sql: {{ .Values.hibernate.show_sql }}  
      globally_quoted_identifiers: {{ .Values.hibernate.globally_quoted_identifiers }}  
    # redis
    redis:
      host: {{ template "redisConnection.host" . }}
      port: {{ .Values.redisConnection.port }}
