apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trino-gateway-proxy-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.certManager.clusterIssue }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
    - host: {{ .Values.ingress.proxyHostName }}
      http:
        paths:
          - backend:
              service:
                name: trino-gateway-proxy-service
                port:
                  number: {{ .Values.trino.proxy.port }}
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - {{ .Values.ingress.proxyHostName }}
      secretName: {{ .Values.ingress.proxyHostName }}-tls