apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trino-gateway-rest-ingress
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
    - host: {{ .Values.ingress.restHostName }}
      http:
        paths:
          - backend:
              service:
                name: trino-gateway-rest-service
                port:
                  number: {{ .Values.server.port }}
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - {{ .Values.ingress.restHostName }}
      secretName: {{ .Values.ingress.restHostName }}-tls