apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: trino-gateway-rest-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.ingressClassName }}
    cert-manager.io/cluster-issuer: {{ .Values.certManager.clusterIssue }}
spec:
  rules:
    - host: {{ .Values.ingress.restHostName }}
      http:
        paths:
          - backend:
              serviceName: trino-gateway-rest-service
              servicePort: {{ .Values.server.port }}
            path: /
  tls:
    - hosts:
        - {{ .Values.ingress.restHostName }}
      secretName: {{ .Values.ingress.restHostName }}-tls