apiVersion: v1
kind: Service
metadata:
  name: trino-gateway-proxy-service
  namespace: {{ namespace }}
  labels:
    app: trino-gateway
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.trino.proxy.port }}
      targetPort: trino-gateway-proxy
      protocol: TCP
      name: trino-gateway-proxy
  selector:
    app: trino-gateway

---
apiVersion: v1
kind: Service
metadata:
  name: trino-gateway-rest-service
  namespace: {{ namespace }}
  labels:
    app: trino-gateway
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.server.port }}
      targetPort: trino-gateway-rest
      protocol: TCP
      name: trino-gateway-rest
  selector:
    app: trino-gateway
