apiVersion: v1
kind: Secret
metadata:
  name: s3-secret
  namespace: {{ operatorNamespace }}
type: Opaque
data:
  accessKey: $(echo -n "{{ accessKey }}" | base64)
  secretKey: $(echo -n "{{ secretKey }}" | base64)