apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ pvcName }}
  namespace: {{ namespace }}
  labels: {}
  annotations: {}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ size }}Gi
  storageClassName: nfs
